### ISSUE TITLE
How to add to https://containers.dev/

### ISSUE THREAD

**Issue by ianpurton** [purton-tech/rust-on-nails#26]
- [x] Run the CI to create a tarball
- [x] Copy stuff over from https://github.com/devcontainers/template-starter
- [x] npm install -g @devcontainers/cli
- [x] figure out how to use command to generate stuff.
- [x] Get CI CD working.
- [x] How do we test it
- [ ] [collection-index.yml](https://github.com/devcontainers/devcontainers.github.io/blob/gh-pages/_data/collection-index.yml)

```yaml
- name: UNSW cs3231 OS Development
  maintainer: Hamish Cox
  contact: https://github.com/HamishWHC/cs3231-devcontainer/issues
  repository: https://github.com/HamishWHC/cs3231-devcontainer
  ociReference: ghcr.io/hamishwhc/cs3231-devcontainer
```

```yaml
- name: Rust on Nails
  maintainer: Ian Purton
  contact: https://github.com/purton-tech/rust-on-nails/issues
  repository: https://github.com/purton-tech/rust-on-nails
  ociReference: ghcr.io/purton-tech/rust-on-nails
```
